docker: decorrelate coog scripts from docker entrypoint: fix #3509

diff --git a/bin/docker-ep b/bin/docker-ep
--- a/bin/docker-ep
+++ b/bin/docker-ep
@@ -1,31 +1,31 @@
-# vim: set ft=sh:
+#!/bin/sh
 # docker entrypoint
 
-_coog_ep_conf_file() {
+ep_conf_file() {
         echo `readlink -f ../../coog.conf`
 }
 
-_coog_ep_data_folder() {
+ep_data_folder() {
         echo `readlink -f ../../data`
 }
 
-_coog_ep_conf_jsonrpc() {
+ep_conf_jsonrpc() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         echo "[jsonrpc]" >> $file
         echo "listen = 0.0.0.0:8000" >> $file
 }
 
-_coog_ep_conf_xmlrpc() {
+ep_conf_xmlrpc() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         echo "[xmlrpc]" >> $file
         echo "listen = 0.0.0.0:8069" >> $file
 }
 
-_coog_ep_conf_database() {
+ep_conf_database() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         echo "[database]" >> $file
         local db_system
         [ ! -z $COOG_DB_SYS ] && db_system=$COOG_DB_SYS
@@ -55,20 +55,22 @@ _coog_ep_conf_database() {
         [ -z $db_password ] && echo "  no db password defined" && return 1
         echo "uri = $db_system://$db_user:$db_password@$db_host:$db_port" >> $file
         local db_data
-        db_data=`_coog_ep_data_folder`
+        db_data=`ep_data_folder`
         echo "path = $db_data" >> $file
+        [ ! -z $COOG_DB_LANG ] && echo "language = $COOG_DB_LANG" >> $file
+        return 0
 }
 
-_coog_ep_conf_cache() {
+ep_conf_cache() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         echo "[cache]" >> $file
         local cache_host
         [ ! -z $COOG_CACHE_HOST ] && cache_host=$COOG_CACHE_HOST
         [ -z $cache_host ] && \
                 [ ! -z $REDIS_PORT_6379_TCP_ADDR ] && \
                 cache_host=$REDIS_PORT_6379_TCP_ADDR
-        [ -z $cache_host ] && return
+        [ -z $cache_host ] && return 0
         local cache_port
         [ ! -z $COOG_CACHE_PORT ] && cache_port=$COOG_CACHE_PORT
         [ -z $cache_port ] && \
@@ -81,13 +83,22 @@ _coog_ep_conf_cache() {
         echo "redis = redis://$cache_host:$cache_port/$cache_db" >> $file
 }
 
-_coog_ep_conf_sentry() {
+ep_conf_session() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
+        echo "[session]" >> $file
+        local password
+        password=`cat ../../.password`
+        echo "super_pwd = $password" >> $file
+}
+
+ep_conf_sentry() {
+        local file
+        file=`ep_conf_file`
         echo "[sentry]" >> $file
         local sentry_host
         [ ! -z $COOG_SENTRY_HOST ] && sentry_host=$COOG_SENTRY_HOST
-        [ -z $sentry_host ] && return
+        [ -z $sentry_host ] && return 0
         local sentry_protocol
         [ ! -z $COOG_SENTRY_PROTOCOL ] && sentry_protocol=$COOG_SENTRY_PROTOCOL
         [ -z $sentry_protocol ] && sentry_protocol=http
@@ -96,51 +107,73 @@ _coog_ep_conf_sentry() {
         [ -z $sentry_port ] && sentry_port=9000
         local sentry_pub
         [ ! -z $COOG_SENTRY_PUB ] && sentry_pub=$COOG_SENTRY_PUB
-        [ -z $sentry_pub ] && echo no sentry dsn pub key defined && return -1
+        [ -z $sentry_pub ] && echo no sentry dsn pub key defined && return 1
         local sentry_sec
         [ ! -z $COOG_SENTRY_SEC ] && sentry_sec=$COOG_SENTRY_SEC
-        [ -z $sentry_sec ] && echo no sentry dsn sec key defined && return -1
+        [ -z $sentry_sec ] && echo no sentry dsn sec key defined && return 1
         local sentry_project
         [ ! -z $COOG_SENTRY_PROJECT ] && sentry_project=$COOG_SENTRY_PROJECT
-        [ -z $sentry_project ] && echo no sentry dsn project defined && return -1
+        [ -z $sentry_project ] && echo no sentry dsn project defined && return 1
         echo "dsn = $sentry_protocol://$sentry_pub:$sentry_sec@$sentry_host:$sentry_port/$sentry_project" >> $file
 }
 
-_coog_ep_conf() {
+ep_conf() {
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         echo "# Coog configuration" > $file
-        _coog_ep_conf_jsonrpc && \
-                _coog_ep_conf_xmlrpc && \
-                _coog_ep_conf_database && \
-                _coog_ep_conf_cache && \
-                _coog_ep_conf_sentry
+        ep_conf_jsonrpc && \
+                ep_conf_xmlrpc && \
+                ep_conf_database && \
+                ep_conf_cache && \
+                ep_conf_session && \
+                ep_conf_sentry
 }
 
-coog_ep_app() { # start Coog app inside container
-        echo Welcome on board, Coog is getting started
-        echo
+config() { # print container built config file
         echo Building configuration file...
-        _coog_ep_conf || ( echo "!!! Failed to build configuration file !!!" && return )
-
-        echo
-        echo Staring Coog...
-        local file
-        file=`_coog_ep_conf_file`
-        trytond -c $file $*
-}
-
-coog_ep_config() { # print container built config file
-        echo Building configuration file...
-        _coog_ep_conf || ( echo "!!! Failed to build configuration file !!!" && return )
-
+        ep_conf || ( echo "!!! Failed to build configuration file !!!" && return 1 )
         echo
         echo Built configuration:
         local file
-        file=`_coog_ep_conf_file`
+        file=`ep_conf_file`
         cat $file
 }
 
-coog_ep_version() { # print image repos versions
+app() { # start Coog app inside container
+        echo Welcome on board, Coog is getting started
+        echo
+        echo Building configuration file...
+        ep_conf || ( echo "!!! Failed to build configuration file !!!" && return 1 )
+        echo
+        echo Staring Coog...
+        local file
+        file=`ep_conf_file`
+        trytond -c $file $*
+}
+
+version() { # print image repos versions
         cat ../../.version
 }
+
+dep() {
+        . ./coog-dep
+        coog_dep_base && coog_dep_extend
+}
+
+link() {
+        . ./coog-repo
+        coog_repo_linkm
+}
+
+main() {
+        local script_path=`readlink -f $0`
+        local script_dir=`dirname $script_path`
+        cd $script_dir
+        [ "$1" = dep ] && shift && dep $* && return $?
+        [ "$1" = link ] && shift && link $* && return $?
+        [ "$1" = version ] && shift && version $* && return $?
+        [ "$1" = config ] && shift && config $* && return $?
+        [ "$1" = app ] && shift && app $* && return $?
+}
+
+main $*
