docker: support batch and unoconv: fix #3572

diff --git a/bin/docker-ep b/bin/docker-ep
--- a/bin/docker-ep
+++ b/bin/docker-ep
@@ -3,182 +3,301 @@
 
 COOG_ROOT=/opt/coog
 COOG_TRYTOND=$COOG_ROOT/trytond
+COOG_BIN=$COOG_ROOT/coog/bin
+COOG_CONF=$COOG_ROOT/coog.conf
+COOG_DATA=$COOG_ROOT/data
 
-ep_conf_file() {
-        echo `readlink -f $COOG_ROOT/coog.conf`
+###########
+# helpers #
+###########
+
+linked_redis_host() {
+        echo $REDIS_PORT_6379_TCP_ADDR
 }
 
-ep_data_folder() {
-        echo `readlink -f $COOG_ROOT/data`
+linked_redis_port() {
+        echo $REDIS_PORT_6379_TCP_PORT
 }
 
-ep_conf_jsonrpc() {
-        local file
-        file=`ep_conf_file`
-        echo "[jsonrpc]" >> $file
-        echo "listen = 0.0.0.0:8000" >> $file
+linked_postgres_host() {
+        echo $POSTGRES_PORT_5432_TCP_ADDR
 }
 
-ep_conf_xmlrpc() {
-        local file
-        file=`ep_conf_file`
-        echo "[xmlrpc]" >> $file
-        echo "listen = 0.0.0.0:8069" >> $file
+linked_postgres_port() {
+        echo $POSTGRES_PORT_5432_TCP_PORT
 }
 
-ep_conf_database() {
-        local file
-        file=`ep_conf_file`
-        echo "[database]" >> $file
+hash_pwd() {
+        python2 -c "import crypt,random,string; print crypt.crypt('$1', ''.join(random.sample(string.ascii_letters + string.digits, 8)))"
+}
+
+################
+# build config #
+################
+
+conf_jsonrpc() {
+        echo "[jsonrpc]" >> $COOG_CONF
+        echo "listen = 0.0.0.0:8000" >> $COOG_CONF
+}
+
+conf_xmlrpc() {
+        echo "[xmlrpc]" >> $COOG_CONF
+        echo "listen = 0.0.0.0:8069" >> $COOG_CONF
+}
+
+conf_database() {
+        echo "[database]" >> $COOG_CONF
         local db_system
         [ ! -z $COOG_DB_SYS ] && db_system=$COOG_DB_SYS
         [ -z $db_system ] && db_system=postgresql
         local db_host
         [ ! -z $COOG_DB_HOST ] && db_host=$COOG_DB_HOST
-        [ -z $db_host ] && \
-                [ $db_system = postgresql ] && \
-                [ ! -z $POSTGRES_PORT_5432_TCP_ADDR ] && \
-                db_host=$POSTGRES_PORT_5432_TCP_ADDR
-        [ -z $db_host ] && echo "  no db host defined" && return 1
+        [ -z $db_host ] && [ $db_system = postgresql ] && db_host=`linked_postgres_host`
+        [ -z $db_host ] && echo "no db host defined" && return 1
         local db_port
         [ ! -z $COOG_DB_PORT ] && db_port=$COOG_DB_PORT
-        [ -z $db_port ] && \
-                [ $db_system = postgresql ] && \
-                [ ! -z $POSTGRES_PORT_5432_TCP_PORT ] && \
-                db_port=$POSTGRES_PORT_5432_TCP_PORT
-        [ -z $db_port ] && \
-                [ $db_system = postgresql ] && \
-                db_port=5432
-        [ -z $db_port ] && echo "  no db port defined" && return 1
+        [ -z $db_port ] && [ $db_system = postgresql ] && db_port=`linked_postgres_port`
+        [ -z $db_port ] && echo "no db port defined" && return 1
         local db_user
         [ ! -z $COOG_DB_USER ] && db_user=$COOG_DB_USER
-        [ -z $db_user ] && echo "  no db user defined" && return 1
+        [ -z $db_user ] && echo "no db user defined" && return 1
         local db_password
         [ ! -z $COOG_DB_PASSWORD ] && db_password=$COOG_DB_PASSWORD
-        [ -z $db_password ] && echo "  no db password defined" && return 1
-        echo "uri = $db_system://$db_user:$db_password@$db_host:$db_port" >> $file
-        local db_data
-        db_data=`ep_data_folder`
-        echo "path = $db_data" >> $file
-        [ ! -z $COOG_DB_LANG ] && echo "language = $COOG_DB_LANG" >> $file
+        [ -z $db_password ] && echo "no db password defined" && return 1
+        echo "uri = $db_system://$db_user:$db_password@$db_host:$db_port" >> $COOG_CONF
+        echo "path = $COOG_DATA" >> $COOG_CONF
+        [ ! -z $COOG_DB_LANG ] && echo "language = $COOG_DB_LANG" >> $COOG_CONF
         return 0
 }
 
-ep_conf_cache() {
-        local file
-        file=`ep_conf_file`
-        echo "[cache]" >> $file
+conf_cache() {
+        echo "[cache]" >> $COOG_CONF
+        [ ! -z $COOG_CACHE_MODEL ] && echo "model = $COOG_CACHE_MODEL" >> $COOG_CONF
+        [ ! -z $COOG_CACHE_RECORD ] && echo "record = $COOG_CACHE_RECORD" >> $COOG_CONF
+        [ ! -z $COOG_CACHE_FIELD ] && echo "field = $COOG_CACHE_FIELD" >> $COOG_CONF
+        [ ! -z $COOG_CACHE_COOG ] && echo "coog_cache_size = $COOG_CACHE_COOG" >> $COOG_CONF
+        local cache_sys
+        [ ! -z $COOG_CACHE_SYS ] && cache_sys=$COOG_CACHE_SYS
+        [ -z $cache_sys ] && return 0
         local cache_host
         [ ! -z $COOG_CACHE_HOST ] && cache_host=$COOG_CACHE_HOST
-        [ -z $cache_host ] && \
-                [ ! -z $REDIS_PORT_6379_TCP_ADDR ] && \
-                cache_host=$REDIS_PORT_6379_TCP_ADDR
-        [ -z $cache_host ] && return 0
+        [ -z $cache_host ] && cache_host=`linked_redis_host`
+        [ -z $cache_host ] && echo "no cache host defined" && return 1
         local cache_port
         [ ! -z $COOG_CACHE_PORT ] && cache_port=$COOG_CACHE_PORT
-        [ -z $cache_port ] && \
-                [ ! -z $REDIS_PORT_6379_TCP_PORT ] && \
-                cache_port=$REDIS_PORT_6379_TCP_PORT
-        [ -z $cache_port ] && cache_port=6379
+        [ -z $cache_port ] && cache_port=`linked_redis_port`
+        [ -z $cache_port ] && echo "no cache port defined" && return 1
         local cache_db
         [ ! -z $COOG_CACHE_DB ] && cache_db=$COOG_CACHE_DB
-        [ -z $cache_db ] && echo "  no cache db defined" && return 1
-        echo "redis = redis://$cache_host:$cache_port/$cache_db" >> $file
+        [ -z $cache_db ] && echo "no cache db defined" && return 1
+        echo "redis = redis://$cache_host:$cache_port/$cache_db" >> $COOG_CONF
 }
 
-ep_conf_session() {
-        local file
-        file=`ep_conf_file`
-        echo "[session]" >> $file
+conf_async() {
+        echo "[async]" >> $COOG_CONF
+        local async_sys
+        [ ! -z $COOG_ASYNC_SYS ] && async_sys=$COOG_ASYNC_SYS
+        [ -z $async_sys ] && return 0
+        local async_host
+        [ ! -z $COOG_ASYNC_HOST ] && async_host=$COOG_ASYNC_HOST
+        [ -z $async_host ] && async_host=`linked_redis_host`
+        [ -z $async_host ] && echo "no async host defined" && return 1
+        local async_port
+        [ ! -z $COOG_ASYNC_PORT ] && async_port=$COOG_ASYNC_PORT
+        [ -z $async_port ] && async_port=`linked_redis_port`
+        [ -z $async_port ] && echo "no async port defined" && return 1
+        local async_db
+        [ ! -z $COOG_ASYNC_DB ] && async_db=$COOG_ASYNC_DB
+        [ -z $async_db ] && echo "no async db defined" && return 1
+        echo "$async_sys = redis://$async_host:$async_port/$async_db" >> $COOG_CONF
+        [ $COOG_ASYNC_SYS = rq ] && export TRYTOND_ASYNC_RQ="redis://$async_host:$async_port/$async_db"
+        [ $COOG_ASYNC_SYS = celery ] && export TRYTOND_ASYNC_CELERY="redis://$async_host:$async_port/$async_db"
+}
+
+conf_session() {
+        echo "[session]" >> $COOG_CONF
+        [ -z $COOG_SESSION_SUPERPWD ] && return 0
         local password
-        password=`cat $COOG_ROOT/.password`
-        echo "super_pwd = $password" >> $file
+        password=`hash_pwd $COOG_SESSION_SUPERPWD`
+        echo "super_pwd = $password" >> $COOG_CONF
 }
 
-ep_conf_sentry() {
-        local file
-        file=`ep_conf_file`
-        echo "[sentry]" >> $file
-        local sentry_host
-        [ ! -z $COOG_SENTRY_HOST ] && sentry_host=$COOG_SENTRY_HOST
-        [ -z $sentry_host ] && return 0
+conf_report() {
+        echo "[report]" >> $COOG_CONF
+        echo "unoconv = pipe,name=trytond;urp;StarOffice.ComponentContext" >> $COOG_CONF
+}
+
+conf_sentry() {
+        echo "[sentry]" >> $COOG_CONF
         local sentry_protocol
         [ ! -z $COOG_SENTRY_PROTOCOL ] && sentry_protocol=$COOG_SENTRY_PROTOCOL
         [ -z $sentry_protocol ] && sentry_protocol=http
+        local sentry_host
+        [ ! -z $COOG_SENTRY_HOST ] && sentry_host=$COOG_SENTRY_HOST
+        [ -z $sentry_host ] && return 0
         local sentry_port
         [ ! -z $COOG_SENTRY_PORT ] && sentry_port=$COOG_SENTRY_PORT
-        [ -z $sentry_port ] && sentry_port=9000
+        [ -z $sentry_port ] && echo "no sentry port defined" && return 1
         local sentry_pub
         [ ! -z $COOG_SENTRY_PUB ] && sentry_pub=$COOG_SENTRY_PUB
-        [ -z $sentry_pub ] && echo no sentry dsn pub key defined && return 1
+        [ -z $sentry_pub ] && echo "no sentry dsn pub key defined" && return 1
         local sentry_sec
         [ ! -z $COOG_SENTRY_SEC ] && sentry_sec=$COOG_SENTRY_SEC
-        [ -z $sentry_sec ] && echo no sentry dsn sec key defined && return 1
+        [ -z $sentry_sec ] && echo "no sentry dsn sec key defined" && return 1
         local sentry_project
         [ ! -z $COOG_SENTRY_PROJECT ] && sentry_project=$COOG_SENTRY_PROJECT
-        [ -z $sentry_project ] && echo no sentry dsn project defined && return 1
-        echo "dsn = $sentry_protocol://$sentry_pub:$sentry_sec@$sentry_host:$sentry_port/$sentry_project" >> $file
+        [ -z $sentry_project ] && echo "no sentry dsn project defined" && return 1
+        echo "dsn = $sentry_protocol://$sentry_pub:$sentry_sec@$sentry_host:$sentry_port/$sentry_project" >> $COOG_CONF
 }
 
-ep_conf() {
-        local file
-        file=`ep_conf_file`
-        echo "# Coog configuration" > $file
-        ep_conf_jsonrpc && \
-                ep_conf_xmlrpc && \
-                ep_conf_database && \
-                ep_conf_cache && \
-                ep_conf_session && \
-                ep_conf_sentry
+conf_batch() {
+        echo "[batch]" >> $COOG_CONF
+        echo "root_dir = $COOG_DATA" >> $COOG_CONF
 }
 
-config() { # print container built config file
+conf() {
         echo Building configuration file...
-        ep_conf || ( echo "!!! Failed to build configuration file !!!" && return 1 )
-        echo
-        echo Built configuration:
-        local file
-        file=`ep_conf_file`
-        cat $file
+        conf_jsonrpc && \
+                conf_xmlrpc && \
+                conf_database && \
+                conf_cache && \
+                conf_async && \
+                conf_session && \
+                conf_report && \
+                conf_sentry && \
+                conf_batch
+        [ $? -ne 0 ] && echo "!!! Failed to build configuration file !!!" && return 1
+        return 0
 }
 
-app() { # start Coog app inside container
-        echo Welcome on board, Coog is getting started
-        echo
-        echo Building configuration file...
-        ep_conf || ( echo "!!! Failed to build configuration file !!!" && return 1 )
-        echo
-        echo Staring Coog...
-        local file
-        file=`ep_conf_file`
-        export PYTHONUNBUFFERED=1
-        export PYTHONPATH="$COOG_TRYTOND:$PYTHONPATH"
-        trytond -c $file $*
-}
-
-version() { # print image repos versions
-        cat $COOG_ROOT/.version
-}
+###############
+# entrypoints #
+###############
 
 dep() {
-        . ./coog-dep
-        coog_dep_base && coog_dep_extend
+        . $COOG_BIN/coog-dep
+        coog_dep_base && coog_dep_extend && coog_dep_batch
 }
 
 link() {
-        . ./coog-repo
+        . $COOG_BIN/coog-repo
         coog_repo_linkm
 }
 
+version() {
+        cat $COOG_ROOT/.version
+}
+
+print_env() {
+        printenv
+}
+
+print_conf() {
+        conf || return $?
+        cat $COOG_CONF
+}
+
+app() {
+        echo Welcome on board, Coog App is preparing to start
+        conf || return $?
+        echo Starting unoconv...
+        # done twice - unoconv issue - https://github.com/dagwieers/unoconv/issues/326
+        unoconv --listener -c "pipe,name=trytond;urp;StarOffice.ComponentContext" &
+        sleep 3
+        unoconv --listener -c "pipe,name=trytond;urp;StarOffice.ComponentContext" &
+        echo Starting app...
+        export PYTHONUNBUFFERED=1
+        export PYTHONPATH="$COOG_TRYTOND:$PYTHONPATH"
+        local args
+        args="-c $COOG_CONF"
+        [ ! -z $COOG_DB_NAME ] && args="$args -d $COOG_DB_NAME"
+        trytond $args $*
+}
+
+batch_redis() {
+        python2 $COOG_BIN/.py/evalredis.py $* < $COOG_BIN/redis/batch.lua
+}
+
+batch_generate() {
+        [ $# -lt 2 ] && echo missing arguments && return 1
+        local broker; broker=$1; shift
+        local name; name=$1; shift
+        local waiting; waiting=`batch_redis count $broker $name 'wait'` || return 1
+        [ $waiting -ne 0 ] && echo queue not empty && return 1
+        python2 -m "batch" -b $broker -n $name $*
+}
+
+batch_rq() {
+        local i=0
+        while [ $i -lt $2 ]
+        do
+                i=$((i+1))
+                rq worker --burst -u $TRYTOND_ASYNC_RQ -n "$1"-"$i" $1 &
+        done
+}
+
+batch_celery() {
+        celery worker --loglevel=$LOG_LEVEL --app=async.broker_celery --queues=$1 --concurrency=$2 &
+}
+
+batch_wait() {
+        [ $# -lt 2 ] && echo missing arguments && return 1
+        local broker; broker=$1; shift
+        local name; name=$1; shift
+        while [ true ]
+        do
+                local waiting; waiting=`batch_redis count $broker $name 'wait'` || return 1
+                [ $waiting -eq 0 ] && break
+                echo "wait @ "`date +"%H:%M:%S"`" - $waiting"
+                sleep 10
+        done
+        local failed; failed=`batch_redis count $broker $name 'fail'`
+        [ $failed -ne 0 ] && echo "$failed jobs failed" && return 1
+        echo batch execution succeeded && return 0
+}
+
+batch() {
+        echo Welcome on board, Coog Batch is preparing to start
+        conf || return $?
+        [ -z $COOG_ASYNC_SYS ] && echo "no async broker defined" && return 1
+        echo Starting unoconv...
+        # done twice - unoconv issue - https://github.com/dagwieers/unoconv/issues/326
+        unoconv --listener -c "pipe,name=trytond;urp;StarOffice.ComponentContext" &
+        sleep 3
+        unoconv --listener -c "pipe,name=trytond;urp;StarOffice.ComponentContext" &
+        echo Starting batch...
+        export PYTHONUNBUFFERED=1
+        export PYTHONPATH="$COOG_BIN/lib:$COOG_TRYTOND:$PYTHONPATH"
+        export TRYTOND_CONFIG="$COOG_CONF"
+        export DB_NAME=$COOG_DB_NAME
+        export LOG_LEVEL=WARNING
+        local name; name=$1; shift
+        local nb; nb=$1; shift
+        if [ $COOG_ASYNC_SYS = rq ]
+        then
+                batch_generate rq $name $* && batch_rq $name $nb && batch_wait rq $name
+        elif [ $COOG_ASYNC_SYS = celery ]
+        then
+                batch_generate celery $name $* && batch_celery $name $nb && batch_wait celery $name
+        else
+                echo "unknonw async sys" && return 1
+        fi
+}
+
+########
+# main #
+########
+
 main() {
-        local script_path=`readlink -f $0`
-        local script_dir=`dirname $script_path`
-        cd $script_dir
-        [ "$1" = dep ] && shift && dep $* && return $?
-        [ "$1" = link ] && shift && link $* && return $?
-        [ "$1" = version ] && shift && version $* && return $?
-        [ "$1" = config ] && shift && config $* && return $?
-        [ "$1" = app ] && shift && app $* && return $?
+        [ -z $1 ] && echo Possible actions: version - env - config - app - batch && return 1
+        [ $1 = dep ] && { shift; dep $*; return $?; }
+        [ $1 = link ] && { shift; link $*; return $?; }
+        [ $1 = version ] && { shift; version $*; return $?; }
+        [ $1 = env ] && { shift; print_env $*; return $?; }
+        [ $1 = config ] && { shift; print_conf $*; return $?; }
+        [ $1 = app ] && { shift; app $*; return $?; }
+        [ $1 = batch ] && { shift; batch $*; return $?; }
+        echo Not supported action && return 1
 }
 
 main $*
