batch: add a helper to split a failed job: fix #3731

diff --git a/bin/docker-ep b/bin/docker-ep
--- a/bin/docker-ep
+++ b/bin/docker-ep
@@ -224,7 +224,27 @@ batch_generate() {
         local name; name=$1; shift
         local waiting; waiting=`batch_redis count $broker $name 'wait'` || return 1
         [ $waiting -ne 0 ] && echo queue not empty && return 1
-        python2 -m "batch" -b $broker -n $name $*
+        python2 -m "batch-generate" -b $broker -n $name $*
+}
+
+batch_split() {
+        [ $# -lt 2 ] && echo missing arguments && return 1
+        local broker; broker=$1; shift
+        local name; name=$1; shift
+        local waiting; waiting=`batch_redis count $broker $name 'wait'` || return 1
+        [ $waiting -ne 0 ] && echo queue not empty && return 1
+        batch_redis backup $broker $name || return 1
+        local head; head=1
+        batch_redis list $broker $name |
+        while IFS= read -r fail
+        do
+                [ $head -eq 1 ] && head=0 && continue
+                local id; id=`echo $fail | cut -d " " -f 2`
+                local key; key=`batch_redis key $broker $id` || return 1
+                python2 -m "batch-split" $broker $key && batch_redis archive $broker $id
+                [ $? -ne 0 ] && return $?
+        done
+        return 0
 }
 
 batch_rq() {
@@ -252,8 +272,17 @@ batch_wait() {
                 sleep 10
         done
         local failed; failed=`batch_redis count $broker $name 'fail'`
-        [ $failed -ne 0 ] && echo "$failed jobs failed" && return 1
-        echo batch execution succeeded && return 0
+        [ $failed -eq 0 ] && echo batch execution succeeded && return 0
+        echo "$failed jobs failed"
+        local head; head=1
+        batch_redis list $broker $name fail |
+        while IFS= read -r fail
+        do
+                [ $head -eq 1 ] && head=0 && continue
+                local id; id=`echo $fail | cut -d " " -f 2`
+                batch_redis show $broker $id
+                echo
+        done
 }
 
 batch() {
@@ -271,14 +300,25 @@ batch() {
         export TRYTOND_CONFIG="$COOG_CONF"
         export DB_NAME=$COOG_DB_NAME
         export LOG_LEVEL=WARNING
+        local action; action=$1; shift
         local name; name=$1; shift
         local nb; nb=$1; shift
+        local gen_api;
+        if [ $action = exec ]
+        then
+                gen_api=generate
+        elif [ $action = retry ]
+        then
+                gen_api=split
+        else
+                echo "possible actions: exec - retry" && return 1
+        fi
         if [ $COOG_ASYNC_SYS = rq ]
         then
-                batch_generate rq $name $* && batch_rq $name $nb && batch_wait rq $name
+                batch_$gen_api rq $name $* && batch_rq $name $nb && batch_wait rq $name
         elif [ $COOG_ASYNC_SYS = celery ]
         then
-                batch_generate celery $name $* && batch_celery $name $nb && batch_wait celery $name
+                batch_$gen_api celery $name $* && batch_celery $name $nb && batch_wait celery $name
         else
                 echo "unknonw async sys" && return 1
         fi
@@ -289,7 +329,7 @@ batch() {
 ########
 
 main() {
-        [ -z $1 ] && echo Possible actions: version - env - config - app - batch && return 1
+        [ -z $1 ] && echo Possible commands: version - env - config - app - batch && return 1
         [ $1 = dep ] && { shift; dep $*; return $?; }
         [ $1 = link ] && { shift; link $*; return $?; }
         [ $1 = version ] && { shift; version $*; return $?; }
@@ -297,7 +337,7 @@ main() {
         [ $1 = config ] && { shift; print_conf $*; return $?; }
         [ $1 = app ] && { shift; app $*; return $?; }
         [ $1 = batch ] && { shift; batch $*; return $?; }
-        echo Not supported action && return 1
+        echo Not supported command && return 1
 }
 
 main $*
