5085 (#67)
bin: unify redis scripts - smoother coog redis - docker ep for redis: fix #5085

diff --git a/bin/docker/ep b/bin/docker/ep
--- a/bin/docker/ep
+++ b/bin/docker/ep
@@ -168,7 +168,6 @@ print_conf() {
 }
 
 admin() {
-        echo Welcome on board, Coog Admin is preparing to start
         init || return $?
         local args
         args="-c $COOG_CONF_SRV"
@@ -194,20 +193,6 @@ wsgi() {
         uwsgi -T --module trytond.application:app --http :7999 --processes "$1"
 }
 
-batch() {
-        [ -z "$1" ] && echo "missing batch name" && return 1
-        echo Welcome on board, Coog Batch is preparing to start
-        init || return $?
-        . "$COOG_ROOT/coog/bin/coog-redis"
-        . "$COOG_ROOT/coog/bin/coog-celery"
-        . "$COOG_ROOT/coog/bin/coog-rq"
-        . "$COOG_ROOT/coog/bin/coog-batch"
-        coog_batch_generate "$@" || return $?
-        coog_batch_join "$1" && return 0
-        coog_batch_split "$1" || return $?
-        coog_batch_join "$1"
-}
-
 _celery() {
         [ "$#" -lt 2 ] && echo "missing arguments" && return 1
         echo Welcome on board, Coog Celery is preparing to start
@@ -230,6 +215,26 @@ _rq() {
                 "$@"
 }
 
+batch() {
+        [ -z "$1" ] && echo "missing batch name" && return 1
+        init || return $?
+        . "$COOG_ROOT/coog/bin/coog-redis"
+        . "$COOG_ROOT/coog/bin/coog-celery"
+        . "$COOG_ROOT/coog/bin/coog-rq"
+        . "$COOG_ROOT/coog/bin/coog-batch"
+        coog_batch_generate "$@" || return $?
+        coog_batch_join "$1" && return 0
+        coog_batch_split "$1" || return $?
+        coog_batch_join "$1"
+}
+
+redis() {
+        [ -z "$1" ] && echo "missing batch context" && return 1
+        init || return $?
+        . "$COOG_ROOT/coog/bin/coog-redis"
+        coog_redis_eval "$@"
+}
+
 ########
 # main #
 ########
@@ -244,9 +249,10 @@ main() {
         [ "$1" = admin ] && { shift; admin "$@"; return $?; }
         [ "$1" = cron ] && { shift; cron "$@"; return $?; }
         [ "$1" = wsgi ] && { shift; wsgi "$@"; return $?; }
-        [ "$1" = batch ] && { shift; batch "$@"; return $?; }
         [ "$1" = celery ] && { shift; _celery "$@"; return $?; }
         [ "$1" = rq ] && { shift; _rq "$@"; return $?; }
+        [ "$1" = batch ] && { shift; batch "$@"; return $?; }
+        [ "$1" = redis ] && { shift; redis "$@"; return $?; }
         echo "Not supported command" && return 1
 }
 
